# GNUPLOT file generated by OpenCalphad
# OpenCalphad   6.120 :  2026-07-26 : with GNUPLOT fig 1
# subroutine ocplot2B
set terminal wxt size 840,700 font "Arial,16"
#set terminal pdf color solid size 6,5 enhanced font "Arial,16"
#set output "ocgnu.pdf"
set title "OpenCalphad   6.120 :  2026-07-26 : with GNUPLOT fig 1 \n T=X,  P=100000, N=1, X(C)=.01" font "Arial,10" 
set origin 0.0, 0.0 
set size   1.0000,   1.0000
set xlabel "Temperature-K"
set ylabel "Mass fraction of phase,"
set label "~O{.0  C}" at screen 0.02, 0.03 font "Baskerville,20"
set key top right font "Arial,12"
set style line  1 lt  1 lc rgb "#000000" lw 2 pt 10
set style line  2 lt  1 lc rgb "#4169E1" lw 2 pt 6
set style line  3 lt  1 lc rgb "#00C000" lw 2 pt 3
set style line  4 lt  1 lc rgb "#FF0000" lw 2 pt 2
set style line  5 lt  1 lc rgb "#FF00FF" lw 2 pt 4
set style line  6 lt  1 lc rgb "#C8C800" lw 2 pt 5
set style line  7 lt  1 lc rgb "#C0C0C0" lw 2 pt 7
set style line  8 lt  1 lc rgb "#00FFFF" lw 2 pt 8
set style line  9 lt  1 lc rgb "#804080" lw 2 pt 9
set style line 10 lt  1 lc rgb "#7CFF40" lw 2 pt 1
# for invariants, faded read
set style line 100 lt 1 lc rgb "#FF3333" lw 3 pt 1

# Some useful GNUPLOT commands for editing the figure
# ** THIS IS A DASHED LINE (on pdf/wxt):
# set style line 15 lt 0 lc rgb "#C8C800" lw 2 pt 2

# set pointsize 0.6
# set label "text" at 0.5, 0.5 rotate by 60 font "arial,12"
# set xrange [0.5 : 0.7] 
# ** ADDING MANUALLY A LINE AND KEEP SCALING:
# set arrow from x0, y0 to x1,y1 nohead linestyle 1
# ** ADD A RED DOT AT 0.1,1000:
# set obj 1 circle fc rgb "#FF0000" fs sol size 0.02 noclip at 1,1
# ** MODIFY THE PLOTTED VALUE ON AN AXIS:
# plot for [i=] ... using (2*column(i)/(1-2*column(i))):2 with ...
# ** PLOTTING SYMBOLS INSTEAD OF LINE:
# ... using 2:i with points pt 7 ps 3 
# ** OVERLAY PLOTS: 
# set multiplot
# set xrange [] writeback
#  ... plot someting
# set xrange restore
#  ... plot more using same axis scaling 
# unset multiplot



# begin of data with lines     15
$OCT260726105046 << EOD
KEYS:  Temperature-K BPW(BCC-A2) BPW(FCC-A1) BPW(GRAPHITE) 
 # First line: BCC_A2 FCC_A1
   1    1.000000E+03    9.979873E-01 NaN     2.012661E-03
   2    1.000100E+03    9.979875E-01 NaN     2.012461E-03
   3    1.000200E+03    9.979877E-01 NaN     2.012262E-03
   4    1.011173E+03    9.980110E-01    0.000000E+00    1.988992E-03
   5    1.011274E+03    6.999180E-01    3.000820E-01 NaN 
# shift of line   1


   6    1.000000E+03    9.979873E-01 NaN     2.012661E-03
   7    9.999000E+02    9.979871E-01 NaN     2.012860E-03
   8    9.998001E+02    9.979869E-01 NaN     2.013059E-03
   9    9.798001E+02    9.979512E-01 NaN     2.048788E-03
  10    9.598001E+02    9.979227E-01 NaN     2.077278E-03
  11    9.398001E+02    9.979002E-01 NaN     2.099753E-03
  12    9.000000E+02    9.978693E-01 NaN     2.130666E-03
  13    8.000000E+02    9.978385E-01 NaN     2.161542E-03
  14    7.000000E+02    9.978329E-01 NaN     2.167097E-03
  15    6.000000E+02    9.978323E-01 NaN     2.167684E-03
# end of line   2


EOD


plot for [i=3: 5] $OCT260726105046 using 2:i with lines ls (i-2+ 0) title columnheader(i)
pause mouse
